apiVersion: v1
kind: ConfigMap
metadata:
  name: self-hosted-runner-configmap
  namespace: self-hosted-runner
data:
  self-hosted-runner.sh: |
    #!/bin/bash
    su root -c "apt-get update;apt upgrade -yqq;apt -yqq install curl;apt install libicu74 -y"
    useradd user
    RUN_VERSION='2.321.0'
    RUN_REPO='Julie717/kubernetes'
    RUN_TOKEN=`curl -L   -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer <THERE WAS MY_TOKEN>"   -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/Julie717/kubernetes/actions/runners/registration-token | grep "token" |  awk '{ print $2}'| sed 's/.$//'`
    mkdir -p actions-runner && cd actions-runner
    curl -o actions-runner-linux.tar.gz -L https://github.com/actions/runner/releases/download/v${RUN_VERSION}/actions-runner-linux-x64-${RUN_VERSION}.tar.gz
    tar xzf ./actions-runner-linux.tar.gz
    su user -c "yes | ./config.sh --name self_hosted_runner --labels linux,my_runner --runnergroup default --url https://github.com/${RUN_REPO} --token ${RUN_TOKEN}"
    su user -c "yes | ./run.sh"
